### ISSUE TITLE
Change the favicon to GDSC's offficial icon

### ISSUE THREAD

**Issue by Ash-KODES** [GDSC-IET-LUCKNOW/Showcase-Hacktoberfest-2022#23]
You need add GDSC's Logo  in the place of current fav icon.
[GDSC 's Logo ](https://avatars.githubusercontent.com/u/98420409?s=200&v=4)
[How to add FavIcon ](https://www.youtube.com/watch?v=pA8103S-yqk)

**Comment by ayushsaha1018** [comment]
Could you please further explain the issue? 
and assign it to me.
